spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

document:
  batch-size: 50
  log-step-percent: 5
  number-format: "DOC-%06d"

workers:
  submit:
    enabled: true
    cron: "* * * * * *"
    fetch-batch-size: 200
  approve:
    enabled: true
    cron: "* * * * * *"
    fetch-batch-size: 200

server:
  port: 8080

app:
  self-url: localhost:8080

logging:
  level:
    root: info

  application:
    name: docflow-service
